name: Release
on:
  push:
    branches: ['main']
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Define the Checkout step
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      # Define the Setup Node step
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # Define the Install Dependencies step
      - name: Install Dependencies
        run: npm install
      # Define the Test step
      - name: Test
        run: npm run test
      # Define the Coveralls step
      - name: Coveralls
        run: npm run coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      # Define the Build step (Rollup)
      - name: Build
        run: npm run rollup-prod
      # Define the Release step (Semantic Release)
      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
